### ISSUE TITLE
No data since 2017-08-31

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/tamworth#3]
Last record in the csv file was 30-Aug.

**Comment by LoveMyData** [comment]
Error message
```
scraper.rb:10:in `new': no implicit conversion from nil to integer (TypeError)
 	from scraper.rb:10:in `block in scrape_page'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/node_set.rb:186:in `each'
 	from scraper.rb:5:in `scrape_page'
 	from scraper.rb:62:in `<main>'
```
